const state={step:1,plan:'proplus',products:[],images:new Map(),categoryCovers:new Map(),logo:null,coverImage:null,logoPosition:{x:7,y:5},logoSize:18,logoEveryPage:true,history:JSON.parse(localStorage.getItem('catalogHistory')||'[]')};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const normalize=s=>String(s??'').trim().toLowerCase().replace(/\.(jpg|jpeg|png|webp)$/i,'').replace(/\s+/g,'');
const money=v=>Number(String(v??0).replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.'))||0;
const brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const yes=v=>['sim','yes','true','1','x'].includes(String(v??'').trim().toLowerCase());
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fields={code:['código','codigo','cod','sku'],name:['nome','nome do produto','produto','descrição','descricao'],price:['valor','preço','preco'],category:['categoria','category'],new:['novidade','novo'],description:['descrição','descricao','detalhes'],box:['quantidade por caixa','qtd caixa','caixa master'],promo:['promoção','promocao'],production:['em produção','em producao']};

function findValue(row,aliases){const key=Object.keys(row).find(k=>aliases.includes(String(k).trim().toLowerCase()));return key?row[key]:''}
function mapRows(rows){return rows.filter(r=>Object.values(r).some(Boolean)).map((r,i)=>({id:crypto.randomUUID(),code:String(findValue(r,fields.code)||'').trim(),name:String(findValue(r,fields.name)||'').trim(),price:money(findValue(r,fields.price)),category:String(findValue(r,fields.category)||'Sem categoria').trim()||'Sem categoria',isNew:yes(findValue(r,fields.new)),promo:yes(findValue(r,fields.promo)),production:yes(findValue(r,fields.production)),description:String(findValue(r,fields.description)||'').trim(),box:String(findValue(r,fields.box)||'').trim(),order:i,image:null}))}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function goView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const titles={dashboard:['Visão geral','Acompanhe seus catálogos e crie novos projetos.'],builder:['Criar catálogo','Siga as etapas para montar seu catálogo.'],history:['Meus catálogos','Consulte projetos salvos e gerados.'],plans:['Planos','Compare limites e funcionalidades.'],admin:['Administração','Gerencie sua plataforma.']};$('#pageTitle').textContent=titles[id][0];$('#pageSubtitle').textContent=titles[id][1];$('.sidebar').classList.remove('open');if(id==='history')renderHistory();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.onclick=()=>goView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>goView(b.dataset.go));$('#menuToggle').onclick=()=>$('.sidebar').classList.toggle('open');

async function readSheet(file){const status=$('#uploadStatus');status.className='status-box';status.textContent='Lendo e validando a planilha…';try{let rows;if(file.name.toLowerCase().endsWith('.csv')){const text=await file.text();const wb=XLSX.read(text,{type:'string'});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}else{const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}state.products=mapRows(rows);matchImages();renderValidation();renderProductTable();renderCategoryCoverEditor();renderPreview();status.textContent=`${state.products.length} produtos importados com sucesso.`;toast('Planilha importada')}catch(e){status.className='status-box error';status.textContent='Não foi possível ler a planilha. Verifique o formato e os cabeçalhos.';console.error(e)}}
async function readImages(files){const status=$('#uploadStatus');status.className='status-box';status.textContent='Processando imagens…';for(const file of files){if(file.name.toLowerCase().endsWith('.zip')){const zip=await JSZip.loadAsync(file);for(const [name,item] of Object.entries(zip.files)){if(!item.dir&&/\.(jpe?g|png|webp)$/i.test(name)){const blob=await item.async('blob');state.images.set(normalize(name.split('/').pop()),URL.createObjectURL(blob))}}}else if(/^image\//.test(file.type)||/\.(jpe?g|png|webp)$/i.test(file.name)){state.images.set(normalize(file.name),URL.createObjectURL(file))}}matchImages();renderValidation();renderProductTable();renderPreview();const matched=state.products.filter(p=>p.image).length;const missing=state.products.filter(p=>!p.image).length;status.textContent=`${state.images.size} imagens processadas • ${matched} produtos com foto${missing?` • ${missing} sem foto`:''}.`;toast(`${matched} produtos vinculados às fotos`)}
function matchImages(){state.products.forEach(p=>p.image=state.images.get(normalize(p.code))||null)}
function renderValidation(){if(!state.products.length)return;const codes=state.products.map(p=>normalize(p.code));const duplicates=codes.filter((v,i)=>v&&codes.indexOf(v)!==i);const missing=state.products.filter(p=>!p.image).length;const invalid=state.products.filter(p=>!p.code||!p.name).length;const box=$('#validationSummary');box.classList.remove('hidden');box.innerHTML=`<div><strong>${state.products.length}</strong>produtos</div><div><strong>${missing}</strong>sem imagem</div><div><strong>${new Set(duplicates).size+invalid}</strong>inconsistências</div>`}
function renderProductTable(){const wrap=$('#productTableWrap');if(!state.products.length){wrap.classList.add('hidden');return}wrap.classList.remove('hidden');$('#productTable').innerHTML=state.products.slice(0,100).map(p=>`<tr><td>${escapeHtml(p.code)||'<b>Ausente</b>'}</td><td>${escapeHtml(p.name)||'<b>Ausente</b>'}</td><td>${escapeHtml(p.category)}</td><td>${brl(p.price)}</td><td>${p.image?`<img src="${p.image}" alt="">`:'Sem foto'}</td></tr>`).join('')}
function renderCategoryCoverEditor(){const root=$('#categoryCoverList');if(!root)return;const categories=[...new Set(state.products.map(p=>p.category))];if(!categories.length){root.innerHTML='<div class="status-box">Importe uma planilha para visualizar as categorias.</div>';return}root.innerHTML=categories.map(category=>{if(!state.categoryCovers.has(category))state.categoryCovers.set(category,{color:$('#primaryColor').value,image:null});const cover=state.categoryCovers.get(category);return `<div class="category-cover-row" data-category="${escapeHtml(category)}"><strong>${escapeHtml(category)}</strong><label title="Cor da capa"><input class="category-color" type="color" value="${cover.color}"></label>${state.plan==='proplus'?`<label class="category-image-field"><input class="category-image" type="file" accept="image/png,image/jpeg,image/webp"></label>`:'<span class="locked">Imagem disponível no Pro Plus</span>'}</div>`}).join('');$$('.category-cover-row').forEach(row=>{const category=row.dataset.category;row.querySelector('.category-color').oninput=e=>{state.categoryCovers.get(category).color=e.target.value;renderPreview()};const input=row.querySelector('.category-image');if(input)input.onchange=e=>{const file=e.target.files[0];if(file){state.categoryCovers.get(category).image=URL.createObjectURL(file);renderPreview();toast(`Capa de ${category} atualizada`)}}})}

function config(){return{project:$('#projectName').value||'Novo catálogo',company:$('#companyName').value||'Minha Empresa',title:$('#coverTitle').value||'Catálogo Geral',whatsapp:$('#whatsapp').value,website:$('#website').value,template:$('#template').value,perPage:Number($('#perPage').value),primary:$('#primaryColor').value,accent:$('#accentColor').value,group:$('#groupCategory').checked,showPrice:$('#showPrice').checked,showDescription:$('#showDescription').checked,showCode:$('#showCode').checked}}
function productCard(p,c){return `<article class="product-card">${p.isNew?'<span class="badge">NOVIDADE</span>':p.promo?'<span class="badge">PROMOÇÃO</span>':''}${p.image?`<img src="${p.image}" alt="${escapeHtml(p.name)}">`:'<div class="image-placeholder">IMAGEM NÃO ENCONTRADA</div>'}${c.showCode?`<span class="code">CÓD. ${escapeHtml(p.code)}</span>`:''}<h4>${escapeHtml(p.name)}</h4>${c.showDescription&&p.description?`<p>${escapeHtml(p.description)}</p>`:''}${p.box?`<p>Caixa: ${escapeHtml(p.box)} unidades</p>`:''}${c.showPrice?`<strong class="price">${brl(p.price)}</strong>`:''}</article>`}
function logoMarkup(isCover=false){if(!state.logo||(!isCover&&!state.logoEveryPage))return'';return `<img class="catalog-logo" draggable="false" style="left:${state.logoPosition.x}%;top:${state.logoPosition.y}%;width:${state.logoSize}%" src="${state.logo}" alt="Logo">`}
function renderPreview(){const c=config();const root=$('#catalogPreview');root.style.setProperty('--catalog-primary',c.primary);root.style.setProperty('--catalog-accent',c.accent);let pages=[`<section class="a4-page cover-page">${state.coverImage?`<img class="cover-bg" src="${state.coverImage}" alt="Imagem da capa"><span class="cover-overlay"></span>`:''}<small>${escapeHtml(c.company).toUpperCase()}</small>${logoMarkup(true)}<h2>${escapeHtml(c.title)}</h2><p>${escapeHtml([c.whatsapp,c.website].filter(Boolean).join('  •  ')||'Coleção 2026')}</p></section>`];const groups=c.group?Object.groupBy?Object.groupBy(state.products,p=>p.category):state.products.reduce((a,p)=>((a[p.category]??=[]).push(p),a),{}):{'Produtos':state.products};for(const [category,items] of Object.entries(groups)){const categoryCover=state.categoryCovers.get(category)||{color:c.primary,image:null};if(c.group&&items.length)pages.push(`<section class="a4-page category-page" style="background:${categoryCover.color}">${state.plan==='proplus'&&categoryCover.image?`<img class="category-bg" src="${categoryCover.image}" alt="Capa ${escapeHtml(category)}"><span class="category-overlay"></span>`:''}${logoMarkup()}<small>CATEGORIA</small><h2>${escapeHtml(category)}</h2></section>`);for(let i=0;i<items.length;i+=c.perPage){const chunk=items.slice(i,i+c.perPage);const cols=c.perPage===1?1:c.perPage===2?2:2;pages.push(`<section class="a4-page">${logoMarkup()}<header class="page-header"><h3>${escapeHtml(category)}</h3><small>${escapeHtml(c.company)}</small></header><div class="product-grid" style="--catalog-cols:${cols}">${chunk.map(p=>productCard(p,c)).join('')}</div><footer class="page-footer"><span>${escapeHtml(c.website||c.company)}</span><span>${pages.length+1}</span></footer></section>`)}}root.innerHTML=pages.join('');$('#previewPages').textContent=`${pages.length} página${pages.length===1?'':'s'}`;enableLogoDrag()}
function syncLogoPosition(){$$('.catalog-logo').forEach(el=>{el.style.left=`${state.logoPosition.x}%`;el.style.top=`${state.logoPosition.y}%`;el.style.width=`${state.logoSize}%`})}
function enableLogoDrag(){const logos=$$('.catalog-logo');if(!logos.length)return;logos.forEach(logo=>{const page=logo.closest('.a4-page');if(!page)return;logo.onpointerdown=e=>{e.preventDefault();e.stopPropagation();logo.setPointerCapture(e.pointerId);const logoRect=logo.getBoundingClientRect();const offsetX=e.clientX-logoRect.left;const offsetY=e.clientY-logoRect.top;const move=ev=>{const freshPage=page.getBoundingClientRect();const freshLogo=logo.getBoundingClientRect();const maxX=Math.max(0,100-(freshLogo.width/freshPage.width)*100);const maxY=Math.max(0,100-(freshLogo.height/freshPage.height)*100);state.logoPosition.x=Math.max(0,Math.min(maxX,((ev.clientX-freshPage.left-offsetX)/freshPage.width)*100));state.logoPosition.y=Math.max(0,Math.min(maxY,((ev.clientY-freshPage.top-offsetY)/freshPage.height)*100));syncLogoPosition()};const end=()=>{logo.onpointermove=null;logo.onpointerup=null;logo.onpointercancel=null;toast('Posição do logo atualizada em todas as páginas')};logo.onpointermove=move;logo.onpointerup=end;logo.onpointercancel=end}})}
function installLogoEditor(){if($('#logoSizeControl'))return;const box=$('.proplus-feature');if(!box)return;const style=document.createElement('style');style.textContent=`.catalog-logo{position:absolute;height:auto;max-width:none;max-height:none;object-fit:contain;cursor:move;touch-action:none;user-select:none;-webkit-user-drag:none;z-index:8}.logo-editor-controls{margin-top:14px;padding-top:13px;border-top:1px solid #d9c9f4;display:grid;gap:11px}.logo-editor-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.logo-editor-row label,.logo-editor-toggle{font-size:10px!important;color:#52328c!important;font-weight:700!important}.logo-editor-row input[type=range]{grid-column:1/-1;width:100%;accent-color:#6c43ad}.logo-editor-value{font-size:10px;font-weight:800;color:#6c43ad;background:#eee5ff;padding:4px 7px;border-radius:6px}.logo-editor-toggle{display:flex!important;grid-template-columns:18px 1fr!important;align-items:center!important;gap:8px!important}.logo-editor-toggle input{width:16px!important;accent-color:#6c43ad}.logo-reset{justify-self:start;border:1px solid #c9b4f4;background:#fff;color:#6c43ad;border-radius:8px;padding:7px 10px;font:700 9px Inter;cursor:pointer}`;document.head.appendChild(style);box.insertAdjacentHTML('beforeend',`<div class="logo-editor-controls"><div class="logo-editor-row"><label for="logoSizeControl">Tamanho do logo</label><span id="logoSizeValue" class="logo-editor-value">${state.logoSize}%</span><input id="logoSizeControl" type="range" min="5" max="45" step="1" value="${state.logoSize}"></div><label class="logo-editor-toggle"><input id="logoEveryPage" type="checkbox" ${state.logoEveryPage?'checked':''}> Mostrar o logo em todas as páginas</label><button id="logoReset" type="button" class="logo-reset">Restaurar posição e tamanho</button><span class="logo-position-help">Arraste o logo em qualquer página da prévia. A posição e o tamanho serão repetidos em todas as páginas e no PDF.</span></div>`);$('#logoSizeControl').oninput=e=>{state.logoSize=Number(e.target.value);$('#logoSizeValue').textContent=`${state.logoSize}%`;renderPreview()};$('#logoEveryPage').onchange=e=>{state.logoEveryPage=e.target.checked;renderPreview()};$('#logoReset').onclick=()=>{state.logoPosition={x:7,y:5};state.logoSize=18;$('#logoSizeControl').value='18';$('#logoSizeValue').textContent='18%';renderPreview();toast('Logo restaurado')}}
function installPhotoFolderUpload(){if($('#folderImagesInput'))return;const grid=$('.upload-grid');if(!grid)return;const field=document.createElement('label');field.className='dropzone';field.style.gridColumn='1 / -1';field.innerHTML=`<span class="upload-icon">▦</span><strong>Selecionar pasta de fotos</strong><small>Escolha a pasta inteira. Nomeie cada imagem com o código do produto, por exemplo: GP-AT6.jpg</small><input id="folderImagesInput" type="file" accept="image/jpeg,image/png,image/webp" webkitdirectory directory multiple />`;grid.appendChild(field);$('#folderImagesInput').onchange=e=>{const files=[...e.target.files].filter(file=>/^image\//.test(file.type)||/\.(jpe?g|png|webp)$/i.test(file.name));if(!files.length){toast('Nenhuma imagem encontrada na pasta');return}readImages(files)}}
function setStep(step){state.step=Math.max(1,Math.min(4,step));$$('.wizard-step').forEach(p=>p.classList.toggle('active',Number(p.dataset.panel)===state.step));$$('.step').forEach(s=>{const n=Number(s.dataset.step);s.classList.toggle('active',n===state.step);s.classList.toggle('done',n<state.step)});$('#prevStep').disabled=state.step===1;$('#nextStep').style.display=state.step===4?'none':'block';renderPreview();document.querySelector('.wizard-panel').scrollIntoView({behavior:'smooth',block:'start'})}
$('#nextStep').onclick=()=>{if(state.step===2&&!state.products.length){toast('Envie uma planilha antes de continuar');return}setStep(state.step+1)};$('#prevStep').onclick=()=>setStep(state.step-1);$$('.step').forEach(s=>s.onclick=()=>setStep(Number(s.dataset.step)));$('#sheetInput').onchange=e=>e.target.files[0]&&readSheet(e.target.files[0]);$('#imagesInput').onchange=e=>readImages([...e.target.files]);$('#logoInput').onchange=e=>{const f=e.target.files[0];if(f){state.logo=URL.createObjectURL(f);renderPreview();toast('Logo adicionado — arraste na prévia para posicionar')}};
$('#coverImageInput').onchange=e=>{const f=e.target.files[0];if(f){state.coverImage=URL.createObjectURL(f);renderPreview();toast('Imagem da capa adicionada')}};
['projectName','companyName','coverTitle','whatsapp','website','template','perPage','primaryColor','accentColor','groupCategory','showPrice','showDescription','showCode'].forEach(id=>$('#'+id).addEventListener('input',renderPreview));
$('#saveDraft').onclick=()=>{localStorage.setItem('catalogDraft',JSON.stringify({...config(),products:state.products.map(({image,...p})=>p),logoPosition:state.logoPosition,logoSize:state.logoSize,logoEveryPage:state.logoEveryPage,savedAt:new Date().toISOString()}));$('#draftCount').textContent='1';toast('Rascunho salvo neste navegador')};
$('#generatePdf').onclick=async()=>{if(!state.products.length){toast('Importe produtos antes de gerar');return}const box=$('#generationStatus');box.className='status-box';box.textContent='Montando páginas e gerando PDF…';const c=config();try{await html2pdf().set({margin:0,filename:`${c.project.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.pdf`,image:{type:'jpeg',quality:.96},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy'],after:'.a4-page'}}).from($('#catalogPreview')).save();state.history.unshift({id:crypto.randomUUID(),name:c.project,company:c.company,products:state.products.length,pages:$$('.a4-page').length,createdAt:new Date().toISOString()});localStorage.setItem('catalogHistory',JSON.stringify(state.history.slice(0,30)));box.textContent='Catálogo gerado com sucesso.';updateDashboard();toast('PDF gerado com sucesso')}catch(e){box.className='status-box error';box.textContent='Ocorreu um erro ao gerar o PDF.';console.error(e)}};
function renderHistory(){const root=$('#historyList');root.innerHTML=state.history.length?state.history.map(x=>`<article class="history-card"><small>${new Date(x.createdAt).toLocaleString('pt-BR')}</small><h3>${escapeHtml(x.name)}</h3><p>${x.products} produtos • ${x.pages} páginas</p></article>`).join(''):'<div class="catalog-list empty-state"><div class="empty-icon">▤</div><h3>Nenhum catálogo</h3><p>Gere um PDF para iniciar seu histórico.</p></div>'}
function updateDashboard(){const n=state.history.length;$('#catalogCount').textContent=n;$('#adminCatalogCount').textContent=n;$('#draftCount').textContent=localStorage.getItem('catalogDraft')?'1':'0';const recent=$('#recentCatalogs');if(n){recent.classList.remove('empty-state');recent.innerHTML=state.history.slice(0,4).map(x=>`<div style="padding:16px 20px;border-bottom:1px solid #e5ebf0;display:flex;justify-content:space-between"><div><strong style="font-size:12px">${escapeHtml(x.name)}</strong><small style="display:block;color:#7b8c99;margin-top:4px">${x.products} produtos • ${x.pages} páginas</small></div><small>${new Date(x.createdAt).toLocaleDateString('pt-BR')}</small></div>`).join('')}}
installPhotoFolderUpload();installLogoEditor();updateDashboard();renderPreview();